# This is a basic workflow to help you get started with Actions

name: ElectronBuild for Linux

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  BuildForUbuntu:
    runs-on: Ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        name: 'Checkout'
      - uses: actions/setup-node@v1
        with:
          node-version: '14.18'
      - name: package
        run: | 
          npm i
          npm install --global electron-builder
          electron-builder --help 
          electron-builder && ls 
          electron-builder -l
